---
title: "spl_staying_starter script"
output: html_document
date: "2024-04-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load required packages
```{r}
rm(list=ls())
#library(httr)
#library(jsonlite)
library(tidyverse)
library(psych)
library(dplyr)
library(sf)
```

# Getting the data from the Seattle Public Life Database
```{r}
SPL <- read.csv("data_files/Public_Life_Data_-_People_Staying_20240416.csv")
```

# Convert the code into character and create a sub dataset for 2018 and 2023 data
```{r}
#SPL_staying <- fromJSON(rawToChar(SPL$content))

#Create a separate dataset for 2018 and 2023 data
SPL_1823 <- SPL%>%
  filter(study_id=="2018_Seattle_Citywide" | study_id =="2023_Seattle_Citywide")
```

# Rename the gender column: 
```{r}
SPL_1823 <- SPL_1823 %>%
  mutate(
    gender=recode(staying_gender,
                        "Female"="Fem",
                        "Feminine presenting"="Fem",
                        "Gender-non-conforming presenting" = "non_conforming",
                        "Male"="Masc",
                        "Masculine presenting"="Masc",
                        "Other_Unsure"="Unsure",
                        "Unsure"="Unsure"))

table(SPL_1823$gender)
```

# Women/Men Ratio by location
```{r}
FM_ratio <- SPL_1823%>%
  group_by(location_id, gender, study_id)%>%
  dplyr::summarise(count= n())%>%
  pivot_wider(
    id_cols = c(location_id, study_id),
    names_from = gender,
    values_from = count,
    names_prefix = "Observed_"
  )%>%
  mutate(
    FM_ratio = round(Observed_Fem/Observed_Masc, 2)
  )

```

# Merge
```{r}
SPL_1823 <- left_join(SPL_1823, FM_ratio, by=c("location_id","study_id"))
```

# Streets
```{r}
Geospatial <- st_read("https://data.seattle.gov/resource/v4q3-5hvp.geojson")

ggplot(Geospatial)+geom_sf()
```

# Base map: Seattle street map
```{r}
#Seattle street map
map <- st_read("data_files/Seattle_street_map.geojson")

#S_Hood: neighborhood
#L_Hood: district

ggplot(map)+geom_sf(aes(fill=L_HOOD))
```

#Layering: Geospatial data
```{r}
Geospatial <- st_read("https://data.seattle.gov/resource/v4q3-5hvp.geojson")

Polygon <- Geospatial$geometry
class(Polygon) #sfc: simple feature collection

#Get the coordinates of the blocks----
valid_check <- st_is_valid(Polygon)
#One is not valid

Polygon <- Polygon[st_is_valid(Polygon)] #Drop it? overlapping edge

coordinates_block <- st_coordinates(st_centroid(Polygon)) 

##st_centroid computes the geomtric center of the shape
colnames(coordinates_block) <- c("Longitude","Latitude")

coordinates_block <- coordinates_block%>%
  as.matrix()%>%
  st_multipoint()%>%
  st_geometry()%>%
  st_cast(to="POINT")

st_crs(coordinates_block) <- 4326

ggplot(map)+geom_sf()+geom_sf(data=coordinates_block, shape=18, size = 1)+labs(fill="Observation Sites")

```





