---
title: "spl_staying_starter script"
output: html_document
date: "2024-04-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load required packages
```{r}
rm(list=ls())
#library(httr)
#library(jsonlite)
library(tidyverse)
library(psych)
library(dplyr)
library(sf)
```

# Import data
```{r}
SPL <- read.csv("data_files/Public_Life_Data_-_People_Staying_20240416.csv")
locids_nhood_key <- read.csv("data_files/Public_Life_Data_-_Locations_20240422.csv")

locids_geo <- st_read("https://data.seattle.gov/resource/v4q3-5hvp.geojson")
nhoods_geo <- st_read("data_files/Seattle_street_map.geojson")
```

# Convert the code into character and create a sub dataset for 2018 and 2023 data
```{r}
#SPL_staying <- fromJSON(rawToChar(SPL$content))

#Create a separate dataset for 2018 and 2023 data
SPL_1823 <- SPL %>%
  filter(study_id=="2018_Seattle_Citywide" | study_id =="2023_Seattle_Citywide")
```

# Recode the gender column: 
```{r}
SPL_1823 <- SPL_1823 %>%
  mutate(
    gender = recode(staying_gender,
                        "Female" = "Fem",
                        "Feminine presenting" = "Fem",
                        "Gender-non-conforming presenting" = "non_conforming",
                        "Male" = "Masc",
                        "Masculine presenting" = "Masc",
                        "Other_Unsure" = "Unsure",
                        "Unsure" = "Unsure"))

table(SPL_1823$gender)
```

# Create new col for neighborhood
```{r}
locids_nhood_key <- locids_nhood_key %>% select(location_id, location_neighborhood) # select only the neighborhood col we care about
FM_ratio <- left_join(FM_ratio, locids_nhood_key, by = "location_id")
```


# Women/Men Ratio by location
```{r}
FM_ratio <- SPL_1823 %>%
  group_by(location_id, gender, study_id)%>%
  dplyr::summarise(count= n())%>%
  pivot_wider(
    id_cols = c(location_id, study_id),
    names_from = gender,
    values_from = count,
    names_prefix = "Observed_"
  )%>%
  mutate(
    FM_ratio = round(Observed_Fem/Observed_Masc, 2)
  )

head(FM_ratio)
```

# Merge geo data with FM_ratio
```{r}
# first create new col for the neighborhood that each location_id is in by merging in data from Public Life Location dataset
locids_nhood_key <- locids_nhood_key %>% select(location_id, location_neighborhood) # select only the neighborhood col we care about
FM_ratio <- left_join(FM_ratio, locids_nhood_key, by = "location_id")

# merge in location_id shapefiles
FM_ratio <- left_join(FM_ratio, locids_geo, by = "location_id") # merge location_id shape files with FM_ratio
setdiff(FM_ratio$location_id, locids_geo$location_id) #14 location_ids for which we don't have shapefiles
FM_ratio$locids_geo <- FM_ratio$geometry

st_crs(FM_ratio$locids_geo)
st_crs(test$geometry.x)


# merge in neighborhood shapefiles
nhoods_geo_key <- nhoods_geo %>% select(L_HOOD, S_HOOD, geometry)
test <- left_join(FM_ratio, nhoods_geo_key, by = c("location_neighborhood" = "S_HOOD"))
test <- test %>% select(-geometry.x) %>% dplyr::rename(nhoods_geo = geometry.y)
colnames(test)

test %>%
  filter(study_id == "2023_Seattle_Citywide") %>%
ggplot() +
  geom_sf(aes(geometry=nhoods_geo, fill = FM_ratio))

test %>%
  filter(study_id == "2018_Seattle_Citywide") %>%
ggplot() +
  geom_sf(aes(geometry=nhoods_geo, fill = FM_ratio))

```

# Mapping
```{r}
nhoods_geo$S_HOOD
#S_Hood: neighborhood
#L_Hood: district

ggplot() +
  geom_sf(data = nhoods_geo) +
  geom_sf(data = locids_geo, fill = "blue")
```

#Layering: Geospatial data
```{r}
# Geospatial <- st_read("https://data.seattle.gov/resource/v4q3-5hvp.geojson")
# 
# Polygon <- Geospatial$geometry
# class(Polygon) #sfc: simple feature collection
# 
# #Get the coordinates of the blocks----
# valid_check <- st_is_valid(Polygon)
# #One is not valid
# 
# Polygon <- Polygon[st_is_valid(Polygon)] #Drop it? overlapping edge
# 
# coordinates_block <- st_coordinates(st_centroid(Polygon)) 
# 
# ##st_centroid computes the geomtric center of the shape
# colnames(coordinates_block) <- c("Longitude","Latitude")
# 
# coordinates_block <- coordinates_block%>%
#   as.matrix()%>%
#   st_multipoint()%>%
#   st_geometry()%>%
#   st_cast(to="POINT")
# 
# st_crs(coordinates_block) <- 4326
# 
# ggplot(map)+geom_sf()+geom_sf(data=coordinates_block, shape=18, size = 1)+labs(fill="Observation Sites")

```





