---
title: "006_SPL_ageprop_change"
output: html_document
date: "2024-05-20"
---

Plot change in age aproportions between 2018 vs 2023

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load required packages
```{r}
rm(list=ls())
library(tidyverse)
library(psych)
library(dplyr)
library(sf)
library(here)
```

# Import data
```{r}
SPL_1823 <- read.csv(here("data","SPL_1823.csv"))
SEA_map <- st_read(here("data/raw","04_SPL_Seattle_Map.geojson")) # base SEA neighborhood map
```

# Recode the age column 
```{r}
# inspect age col
table(SPL_1823$staying_age, SPL_1823$study_id)
# looks like in 2023 they collapsed 25-44 and 45-64 together into 25-64

SPL_1823 <- SPL_1823 %>%
  mutate(
    age=recode(staying_age,
                        "25-44"="25-64",
                        "45-64"="25-64"))

# table(SPL_1823$age)
# table(SPL_1823$staying_age)
```

# Calculate age proportion by observation site (location_id)
```{r}
age_prop_locid <- SPL_1823 %>%
  group_by(location_id, age, study_id) %>%
  dplyr::summarise(count= n()) %>%
  mutate(age = ifelse(age == "", "NA", age)) %>% #replace the empty strings with NA otherwise it won't pivot
  pivot_wider(
    id_cols = c(location_id, study_id),
    names_from = age,
    values_from = count) %>%
  rowwise() %>% #this is to make sure the total is calculated correctly in the next line
  dplyr::mutate(total = sum(`0-4`, `15-24`, `25-64`, `5-14`, `65+`, `NA`, na.rm=T)) %>% #calculate total observed
  mutate_at(vars(`0-4`, `15-24`, `25-64`, `5-14`, `65+`, `NA`), ~replace_na(., 0)) %>% #replace NAs with 0s so that the calculated proportions return 0 and not NA
  mutate(toddler_prop = `0-4`/total,
         tween_prop = `5-14`/total,
         ya_prop = `15-24`/total, #ya stands for young adult
         adult_prop = `25-64`/total,
         senior_prop = `65+`/total) %>%
  select(location_id, study_id, toddler_prop, tween_prop, ya_prop, adult_prop, senior_prop, total)

# append S_HOOD back
age_prop_locid <- SPL_1823 %>%
  select(location_id, S_HOOD) %>%
  distinct() %>%
  right_join(age_prop_locid, by = "location_id")
```


# 2018 vs 2023 comparisons

## Descriptive Change

```{r}
# raw deltas (2023 - 2018) ------------------------------

# calculate prop age group change by location_id
age_prop_locid_change <- age_prop_locid %>%
  pivot_wider(id_cols = c(location_id, S_HOOD),
              names_from = study_id,
              values_from = c(toddler_prop, tween_prop, ya_prop, adult_prop, senior_prop)) %>%
  rename_with(~str_remove(., '_Seattle_Citywide')) %>% # drop the suffix
  mutate(toddler_prop_2318 = toddler_prop_2023 - toddler_prop_2018,
         tween_prop_2318 = tween_prop_2023 - tween_prop_2018,
         ya_prop_2318 = ya_prop_2023 - ya_prop_2018,
         adult_prop_2318 = adult_prop_2023 - adult_prop_2018,
         senior_prop_2318 = senior_prop_2023 - senior_prop_2018)

age_prop_locid_change %>%
  mutate(across(where(is.numeric), round, 3)) %>%
  arrange(location_id)
# a lot of missing data bc there are many age groups that aren't observed at all at certain locations

which(!is.na(age_prop_locid_change$toddler_prop_2318)) # e.g., there are only 5 locations where there were toddlers observed in 2018 and 2023
```

## Plots

### Scatter x = year, y = proportion
```{r}
## toddler
age_prop_locid %>%
  ggplot(., aes(x = study_id, y = toddler_prop, colour = location_id)) +
  geom_point() +
  geom_line(aes(group = location_id)) + # draw connecting lines between years
  stat_summary(fun = mean, color = "black", geom = "point", shape = 20, size = 3) + # add point for mean
  coord_cartesian(ylim = c(0, 1)) +
  theme(legend.position = "none") +
  labs(x = "Year", y = "Proportion of toddlers") +
  scale_x_discrete(labels = c("2018", "2023"))

ggsave(filename = "1823_toddler_prop_scatterconnect.png", path = here("Visualization"), bg="white", width = 7, height = 7)

## tween
age_prop_locid %>%
  ggplot(., aes(x = study_id, y = tween_prop, colour = location_id)) +
  geom_point() +
  geom_line(aes(group = location_id)) + # draw connecting lines between years
  stat_summary(fun = mean, color = "black", geom = "point", shape = 20, size = 3) + # add point for mean
  coord_cartesian(ylim = c(0, 1)) +
  theme(legend.position = "none") +
  labs(x = "Year", y = "Proportion of tweens") +
  scale_x_discrete(labels = c("2018", "2023"))

ggsave(filename = "1823_tween_prop_scatterconnect.png", path = here("Visualization"), bg="white", width = 7, height = 7)


## young adults
age_prop_locid %>%
  ggplot(., aes(x = study_id, y = ya_prop, colour = location_id)) +
  geom_point() +
  geom_line(aes(group = location_id)) + # draw connecting lines between years
  stat_summary(fun = mean, color = "black", geom = "point", shape = 20, size = 3) + # add point for mean
  coord_cartesian(ylim = c(0, 1)) +
  theme(legend.position = "none") +
  labs(x = "Year", y = "Proportion of young adults") +
  scale_x_discrete(labels = c("2018", "2023"))

ggsave(filename = "1823_ya_prop_scatterconnect.png", path = here("Visualization"), bg="white", width = 7, height = 7)

## adults
age_prop_locid %>%
  ggplot(., aes(x = study_id, y = adult_prop, colour = location_id)) +
  geom_point() +
  geom_line(aes(group = location_id)) + # draw connecting lines between years
  stat_summary(fun = mean, color = "black", geom = "point", shape = 20, size = 3) + # add point for mean
  coord_cartesian(ylim = c(0, 1)) +
  theme(legend.position = "none") +
  labs(x = "Year", y = "Proportion of adults") +
  scale_x_discrete(labels = c("2018", "2023"))

ggsave(filename = "1823_adult_prop_scatterconnect.png", path = here("Visualization"), bg="white", width = 7, height = 7)

## seniors
age_prop_locid %>%
  ggplot(., aes(x = study_id, y = senior_prop, colour = location_id)) +
  geom_point() +
  geom_line(aes(group = location_id)) + # draw connecting lines between years
  stat_summary(fun = mean, color = "black", geom = "point", shape = 20, size = 3) + # add point for mean
  coord_cartesian(ylim = c(0, 1)) +
  theme(legend.position = "none") +
  labs(x = "Year", y = "Proportion of seniors") +
  scale_x_discrete(labels = c("2018", "2023"))

ggsave(filename = "1823_senior_prop_scatterconnect.png", path = here("Visualization"), bg="white", width = 7, height = 7)

```

### Scatter x = 2018 proportion, y = 2023 proportion

```{r}
# toddler
age_prop_locid_change %>%
  filter(!is.na(toddler_prop_2318)) %>%
  ggplot(aes(x = toddler_prop_2018, y = toddler_prop_2023, colour = location_id)) +
  geom_point() +
  geom_abline(slope = 1, linetype="dotted") +
  coord_cartesian(xlim = c(0, 1), ylim = c(0, 1)) +
  theme(legend.position = "none") +
  labs(x = "2018", y = "2023", title = "Proportion of toddlers (0-4 yrs)")

ggsave(filename = "1823_toddler_prop_scatter.png", path = here("Visualization"), bg="white", width = 7, height = 7)

# tween
age_prop_locid_change %>%
  filter(!is.na(tween_prop_2318)) %>%
  ggplot(aes(x = tween_prop_2018, y = tween_prop_2023, colour = location_id)) +
  geom_point() +
  geom_abline(slope = 1, linetype="dotted") +
  coord_cartesian(xlim = c(0, 1), ylim = c(0, 1)) +
  theme(legend.position = "none") +
  labs(x = "2018", y = "2023", title = "Proportion of tweens (5-14 yrs)")

ggsave(filename = "1823_tween_prop_scatter.png", path = here("Visualization"), bg="white", width = 7, height = 7)


# young adult
age_prop_locid_change %>%
  filter(!is.na(ya_prop_2318)) %>%
  ggplot(aes(x = ya_prop_2018, y = ya_prop_2023, colour = location_id)) +
  geom_point() +
  geom_abline(slope = 1, linetype="dotted") +
  coord_cartesian(xlim = c(0, 1), ylim = c(0, 1)) +
  theme(legend.position = "none") +
  labs(x = "2018", y = "2023", title = "Proportion of young adults (15-24 yrs)")

ggsave(filename = "1823_ya_prop_scatter.png", path = here("Visualization"), bg="white", width = 7, height = 7)

# adult
age_prop_locid_change %>%
  filter(!is.na(adult_prop_2318)) %>%
  ggplot(aes(x = adult_prop_2018, y = adult_prop_2023, colour = location_id)) +
  geom_point() +
  geom_abline(slope = 1, linetype="dotted") +
  coord_cartesian(xlim = c(0, 1), ylim = c(0, 1)) +
  theme(legend.position = "none") +
  labs(x = "2018", y = "2023", title = "Proportion of adults (25-64 yrs)")

ggsave(filename = "1823_adult_prop_scatter.png", path = here("Visualization"), bg="white", width = 7, height = 7)


# senior
age_prop_locid_change %>%
  filter(!is.na(senior_prop_2318)) %>%
  ggplot(aes(x = senior_prop_2018, y = senior_prop_2023, colour = location_id)) +
  geom_point() +
  geom_abline(slope = 1, linetype="dotted") +
  coord_cartesian(xlim = c(0, 1), ylim = c(0, 1)) +
  theme(legend.position = "none") +
  labs(x = "2018", y = "2023", title = "Proportion of seniors (65+ yrs)")

ggsave(filename = "1823_senior_prop_scatter.png", path = here("Visualization"), bg="white", width = 7, height = 7)

```

#### Interactive

```{r}
p <- age_prop_locid %>%
  ggplot(., aes(x = study_id, y = toddler_prop, color = S_HOOD)) +
  geom_point(aes(text = paste("Year: ", substr(study_id, start=1, stop=4),
                              "<br>Block Face: ", location_id, 
                              "<br>Percentage of toddlers: ", round(toddler_prop,2),
                              "<br>Total observation: ", total))) +
  geom_line(aes(group = location_id)) + # draw connecting lines
  coord_cartesian(ylim = c(0, 1)) +
  scale_y_continuous(breaks = c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1)) +
  theme(legend.position = "none") +
  labs(x = "Year", y = "Proportion of toddlers") +
  scale_x_discrete(labels = c("2018", "2023"))

ggplotly(p, tooltip = "text")
p

htmlwidgets::saveWidget(p, here("Interactive", "2023_Age_interactive.html"), selfcontained = FALSE, libdir = "libs")
```

## Random Effects Models
```{r}
# random effects model ------------------------------------

## observations aggregated at location_id level
r1_toddlerprop <- lmer(toddler_prop ~ study_id + (1|location_id), data = age_prop_locid)
summary(r1_toddlerprop)

r1_tweenprop <- lmer(tween_prop ~ study_id + (1|location_id), data = age_prop_locid)
summary(r1_tweenprop)

r1_yaprop <- lmer(ya_prop ~ study_id + (1|location_id), data = age_prop_locid)
summary(r1_yaprop)

r1_adultprop <- lmer(adult_prop ~ study_id + (1|location_id), data = age_prop_locid)
summary(r1_adultprop)

r1_seniorprop <- lmer(senior_prop ~ study_id + (1|location_id), data = age_prop_locid)
summary(r1_seniorprop)

```

